@{
    Retries = 7
    Chunk = '4096'
    Method = 'WebRequest'
    Automatic = 'True'
    Suppress = 'True'
    FileName_1 = ''
    Url_1 = ''
    FileName_2 = ''
    Url_2 = ''
    FileName_3 = ''
    Url_3 = ''
    FileName_4 = ''
    Url_4 = ''
    FileName_5 = ''
    Url_5 = ''
    FileName_6 = ''
    Url_6 = ''
    FileName_7 = ''
    Url_7 = ''
    FileName_8 = ''
    Url_8 = ''
    FileName_9 = ''
    Url_9 = ''
}
